version: '3'

services:
  # PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${APP_NAME}/php
    container_name: ${APP_NAME}_app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      l37sg0com_default:


  # NGINX Service
  web:
    image: nginx:alpine
    container_name: ${APP_NAME}_web
    restart: unless-stopped
    tty: true
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      l37sg0com_default:

# Custom networks
networks:
  l37sg0com_default:
    external: true
